name: Deploy images

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
  pull_request:

jobs:
  deploy_images:
    name: Deploy images to ghcr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache gradle configuration
        uses: actions/cache@v2
        with:
          path: .gradle/configuration-cache
          key: ${{ runner.os }}-gradle-conf-cache-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-conf-cache-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: petertrr
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: burrunan/gradle-cache-action@v1
        name: Gradle build with caches caching
        with:
          arguments: :initiative-bot-discord:dockerCreateDockerfile :initiative-bot-discord:runDockerBuildx
          gradle-version: wrapper